# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'TestingChartGrafik' do
  pod 'Charts'

  target 'TestingChartGrafikTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingChartGrafikUITests' do
    # Pods for testing
  end

end
