# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 use_frameworks!


target 'SubmissionDicodingFundamental' do
  # Comment the next line if you don't want to use dynamic frameworks
 
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'SwiftLint'

  # Pods for SubmissionDicodingFundamental

end
